django-json-api/django-rest-framework-json-api

rest_framework_ember/utils.py

hey @jerel, ran into py3 compat issue so added six to fix it... also just noticed you moved this out of ngenworks to a new account, awesome! lmk if you need any help maintaining things etc... cheers

Fixed py3 compat issue

---

rest_framework_json_api/utils.py

StringRelatedField and SlugRelatedField have no equivalent definition in the JSON API Spec and are therefore omitted.

Added support for RelatedFields and their supported variants

---

rest_framework_json_api/renderers.py
rest_framework_json_api/utils.py

Please wait for PR https://github.com/alanjds/drf-nested-routers/pull/50 to be accepted before merging this.

Introduced support for nested relationships urls with drf-nested-routers

---

rest_framework_json_api/renderers.py
rest_framework_json_api/utils.py

Fixed missing attribute to build_json_resource_obj and bug with empty HyperlinkedIdentityField relations

Various fixes

---

example/serializers.py
example/tests/test_serializers.py
rest_framework_json_api/serializers.py

refs django-json-api/django-rest-framework-json-api#181

Fix crash related to Meta.fields / Meta.exlcude

---

README.rst

Fix settings block formatting

---

README.rst

I changed the README to reflect what was discussed in #228

Updated the readme for the testing

---

rest_framework_json_api/utils.py

try to use field.remote_field instead of field.related

---

docs/usage.md

Doc typo fix

---

CHANGELOG.md
rest_framework_json_api/__init__.py

Set release version to 2.3.0.

---

AUTHORS

Fixes nothing - just a missing name in AUTHORS (mine)
Added my contact information to AUTHORS

Missing contribution

---

.gitignore
.travis.yml
tox.ini

Additionally requires uploading of coverage reports so such errors will be caught earlier on.

Fix uploading of codecov reports

---

CHANGELOG.md
docs/pull_request_template.md

This way we keep a clean and readable changelog.

Clarify only user specific change log entries be added

---

docs/conf.py

To add full support for Sphinx 2.0.0 as of PR #605

Adjust sphinx apidoc import as for version 2.0 requires

---

README.rst

Clarify readme to avoid outdated dependencies

---

setup.py

This got mistakenly deleted in #714

Introduce wheel in setup.py again

---

CHANGELOG.md
rest_framework_json_api/__init__.py

Release version 3.0.0. Please only merge this once #723 has been merged.

Release 3.0.0

---

docs/usage.md

Fixed class import typo QueryParameterValidationFilter in usage docs.

Fixed class import typo QueryParameterValidationFilter in usage docs.

---

AUTHORS

Sort lines in `AUTHORS` file by alphabet

Sort AUTHORS file by alphabet

---

README.rst

* Remove gitter chat badge as not being used
* Add PyPI badge

Adjust batches

---

.travis.yml
CHANGELOG.md
README.rst
docs/getting-started.md
setup.py
tox.ini

support only drf 3.12

---

README.rst

Fixes #848 
Change badge to Travis CI.com

Move to Travis CI.com

---

README.rst

Fixing a typo in the action badge url.

Adjust action badge image link to use correct svg

---

CHANGELOG.md
rest_framework_json_api/__init__.py

Release 4.2.1

---

.github/workflows/tests.yml
CHANGELOG.md
README.rst
docs/getting-started.md
setup.py
tox.ini

Added support for Python 3.10

---

tox.ini

See [release notes](https://docs.djangoproject.com/en/4.0/releases/4.0/). A new release will need to be made, hoping that DRF will release a new version compatible with Django 4.0.0 soon as well.

Updated to final Django release 4.0.0

---

CHANGELOG.md
rest_framework_json_api/__init__.py

Fixes #1037
New major release 5.0.0.

Release 5.0.0

---

CHANGELOG.md
rest_framework_json_api/__init__.py

New major release 6.0.0. Major release is needed as support of some library versions have been dropped.

Release 6.0.0

---

README.rst

Use syntax highlighting in readme

Use syntax highlighting in readme

---

example/fixtures/drf_example.json
example/settings/dev.py

Fixes #1103
Adjusted data fixture and set required default auto field.

Repaired example app

---

.github/workflows/tests.yml

This way we will quickly notice when a point release in Python, DRF or Django makes DJA fail.

Set daily schedule for running test jobs

---

.readthedocs.yaml

It seems when adding an RTD yaml file it ignores all settings done in the web interface.

Added requirements.txt and spinx docs location to RTD conf

---

setup.py

Fixes the missing links on the PyPI project page.
Add links to the documentation, change log, source code and issue tracker to the PyPI project page.

Add various links on the PyPI project page

---

CHANGELOG.md
README.rst
docs/getting-started.md
tox.ini

Added support for Django 5.0 as of its [release](https://docs.djangoproject.com/en/5.0/releases/5.0/)

Added support for Django 5.0

---

.github/workflows/tests.yml

Updating of codecov github action trying to solve hanging CodeCov check.

Updated Codecov GitHub action

---

CHANGELOG.md
rest_framework_json_api/__init__.py

After those many changes it is time for a new release.

Release 7.0.0

---

CHANGELOG.md
rest_framework_json_api/__init__.py

New release to solve regression #1228

Release 7.0.1

---

CHANGELOG.md
README.rst
docs/getting-started.md
tox.ini

Added support for Django 5.1 which got released beginning of August. No changes were needed concerning the DJA code.

Added support for Django 5.1

---

CHANGELOG.md
rest_framework_json_api/__init__.py

Another major release, mainly fixing support of `JSON_FORMAT_FIELD_NAMES` and removing OpenAPI schema support.

Release 8.0.0
