rest_framework_json_api/renderers.py, rest_framework_json_api/utils.py
Fixing two issues I've discovered:
1. Override media_type on renderers.JSONRenderer as required by the JSON API 1.0 spec. Ember Data has started sending the required Accept: header causing DRF to return a 406 error code if this isn't set.
2. Encountered an issue whereby read_only relations with a source different than the field name could not resolve their resource types as the queryset field is not set when read_only is set on the field (enforced by DRF). Updated the logic to check for the 'source' field as well.
=> Override media type + check relation.source to find relation type

rest_framework_json_api/exceptions.py
The exception handler expects the error to be a list on line 33. In my
case they were a string, which lead to the split of the string into
multiple errors containing one character
=> Fix for some error messages that were split into several messages

rest_framework_json_api/exceptions.py
When I specified `permission_classes = (permissions.IsAuthenticated,)` and called an API, I got a string error.
This pull request modify `exception_handler` for that case.
Could you take a look and merge this?
Thanks!
=> Modify exception_handler for a string error like AuthenticationError

example/tests/test_model_viewsets.py
I am running Django 1.7, Python 2.7, DRF 3.2 and wanted to look at the state of the tests. The only test failure for this setup was the one modified in the PR.
I noticed that when using Django 1.7 something was fishy using a try/catch on an `AssertionError` to test the legacy DRF case of including `?page=1` to the link. Switching to Django 1.8 (changing nothing else) did not have an issue with the try/except wrapping this assertion. 
Digging further I noticed in Django 1.7 the except raised was `exceptions.AssertionError` and in Django 1.8 the exception raised was a `_pytest.assertion.reinterpret.AssertionError`. (Again, changing nothing else) 
At this point I gave up and rewrote the test to not rely on catching an `AssertionError` as that seemed a bit brittle anyway. Everything now …
=> Django 1.7 Tests Fix - change legacy pagination check

docs/usage.md, rest_framework_json_api/utils.py
Implemented a new option to be able to format the key names in
relations.
=> Feature to format the relation names

rest_framework_json_api/utils.py
Also renders proper json `null` when id is None
=> Prevent django from throwing errors if url is None

rest_framework_json_api/utils.py
Reverts django-json-api/django-rest-framework-json-api#75 as extract_id method is removed in #82
=> Revert "Prevent django from throwing errors if url is None"

rest_framework_json_api/utils.py
=> Don't try to extract data from a non-existent resource instance

rest_framework_json_api/utils.py
Work around the fact that inflection.dasherise does only work from the
underscored state
Referring to
https://github.com/django-json-api/django-rest-framework-json-api/commit/5b6456763ed7cdd51660d5293b66cd899bee7a91#commitcomment-13266779
=> Fix camelcase -> dasherise issue

docs/usage.md, example/tests/test_format_keys.py, example/tests/test_utils.py, rest_framework_json_api/utils.py
=> Added capitalize to the inflection options. camelCase now lowercases first letter

rest_framework_json_api/utils.py
Instead of extracting the resource type for the whole related collection, extract the type for each instance individually. This way, polymorphic relationships (using something like django_polymorphic) are
supported.
This PR addresses an issue raised in https://github.com/django-json-api/django-rest-framework-json-api/issues/77
The next step will be to allow customizing the way the type is extracted for each instance, but I'm not sure how to go about that...
=> Extract type for each related instance

example/models.py, example/tests/test_relations.py, rest_framework_json_api/relations.py, rest_framework_json_api/utils.py
Collaborative effort of @leifurhauks & @jsenecal
This field adds support for JSON API's [Resource Identifier Object](http://jsonapi.org/format/#document-resource-identifier-objects) for related objects.
=> ResourceRelatedField & tests

rest_framework_json_api/utils.py
Extracting the included data for many to one relations failed because the all() function was called on an instance instead of a manager object. The all() call should only happen for ListSerializer.
=> Fix .all() call on instance objects instead of only manager objects

rest_framework_json_api/relations.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py
* Implemented SparseFieldsetsMixin serializer mixin to enable a client to request that an endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] parameter.
Spec [Here](http://jsonapi.org/format/#fetching-sparse-fieldsets)
=> Sparse Fieldsets support

rest_framework_json_api/serializers.py
Allows `model_class` to be optionally defined as a class attribute.
When defined as a class attribute, `model class` may still be
overwritten on instantiation via kwarg.
=> Small change to ResourceIdentifierObjectSerializer

example/serializers.py, example/tests/test_utils.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py
in the included_serializers class attribute, classes may be specified as a
string containing the absolute python path for the desired class. Thus, the
values in included_serializers may be a class, a string with the python path
of the desired class, or 'self' to specify the class of the current serializer.
for example:
```python
from rest_framework_json_api import serializers
from rest_framework_json_api.relations import ResourceRelatedField
from myapp.models import Thing
from anotherapp.serializers import CategorySerializer
class ThingSerializer(serializers.HyperlinkedModelSerializer):
class Meta:
model = Thing
serializer_related_field = ResourceRelatedField
included_serializers = {
'category': CategorySerializer,
'accessories': 'myapp.serializers.AccessorySerializer',
'related_things': …
```
=> included_serializers may be specified with strings

rest_framework_json_api/utils.py
fix a bug that caused a 500 error when a to-one related field specified in the
include parameter has a value of null
=> bugfix in extract_included

rest_framework_json_api/utils.py
The behaviour defined in https://github.com/django-json-api/django-rest-framework-json-api/pull/94 was broken at some point. This commit fixes it.
=> Fix regression for related instances type

rest_framework_json_api/metadata.py
In the body of responses to OPTIONS requests, add an attribute
'allows_include' to related fields indicating whether the endpoint
supports including this resource via the include parameter.
=> In OPTIONS responses, indicate include support

rest_framework_json_api/renderers.py
Previously, the renderer would check whether `view.action` was `'list'`,
and if not it would assume the data was a single resource instance.
This can cause problems when a custom route returns list data.
With this commit, the renderer instead checks whether the serializer
that produced that data has `many` set to True.
=> Change in how the renderer detects list data

rest_framework_json_api/utils.py
When getting a list and including data from the models in the list, only
the related data of the first model in the list was included
Explanation:
Let's assume a Model `M` that has a foreign key `type` referencing `Type`. Now we get a list of `M` which have different types and include the types (?include=type), only the `Type` of the first reference will be included, because of line 417.
=> Fix the inclusion of relations

rest_framework_json_api/utils.py
Reverts django-json-api/django-rest-framework-json-api#127
This broke many things using the include parameter.
@schtibe could you please document your issue in a proper 'issue' so that we can work on this ?
=> Revert "Fix the inclusion of relations"

rest_framework_json_api/utils.py
Namely what should be a list of records like [1, 2, 3] becomes
[1, 1, 2]. The solution is to cast to a list first.
I've verified the fix with tests in my private project and I plan to write a test for this before it's merged. If someone needs it in the meantime here it is.
=> Accessing by index on Model.objects.all() produces weird behavior

.travis.yml, requirements-development.txt, rest_framework_json_api/metadata.py, rest_framework_json_api/views.py, tox.ini
* required bumping the pytest version, doesn't seem to cause any issues
* tox base python set to 3.5 so it's available for tox
(tests are getting long, probably OK to drop Python 3.2 support, maybe 3.3 as well?)
=> test on Python 3.5

.travis.yml, rest_framework_json_api/metadata.py, rest_framework_json_api/views.py, tox.ini
* added appropriate lines to travis/tox for Django 1.9 on Py2.7 and 3.4 (3.2/3.3 not supported by Django 1.9)
* fixed two issues caused by https://github.com/django/django/commits/stable/1.9.x/django/db/models/fields/related_descriptors.py changes
=> start testing on Django 1.9a1 and get tests passing

example/tests/integration/test_includes.py, rest_framework_json_api/utils.py
=> Better tests for compound documents - fix for #131

rest_framework_json_api/utils.py
=> Fix for inclusion of nested relations

example/serializers.py, rest_framework_json_api/relations.py
This refactor separates the dynamic related data feature introduced
in #146 from the regular ResourceRelatedField, instead placing it
in the new SerializerMethodResourceField. As discussed on gitter.
=> SerializerMethodResourceField

rest_framework_json_api/relations.py
For this (incorrect) but natural payload the related field would `json.loads`
the `bar` related attribute:
``` py
{
"data": {
"type": "foo",
"attributes": {
"bar": "1",
}
}
}
```
a json ValueError would be thrown instead of the more helpful
"Expected resource identifier object, received unicode"
=> When a `pk` was used as a relationship value a json error was thrown

example/tests/integration/test_sparse_fieldsets.py, rest_framework_json_api/serializers.py
With Python 3.5, using sparse fieldsets causes a `RuntimeError: OrderedDict mutated during iteration`. 
This patch fixes the bug, in `SparseFieldsetMixin`, by iterating over a copy of the `OrderedDict`, so that the original may be modified in the loop.
The `OrderedDict` in question is the underlying `OrderedDict` of the `BindingDict` returned by the `fields` property on `Serializer`.
If curious, see section [4.10.1](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects) of the python standard library docs for more information about why this RuntimeError was being thrown in the first place.
=> Fix sparse fieldset RuntimeError under python3.5

example/factories/__init__.py, example/models.py, example/serializers.py, example/tests/conftest.py, example/tests/integration/test_includes.py, rest_framework_json_api/renderers.py
I have three models:
* Account
* AccountTypeA
* AccountTypeB
AccountTypeA/AccountTypeB each have a OneToOneField to Account. Account can only be of type A or B, not both. In my AccountSerializer I've included the attributes for both the reversed relationships. I've also included the AccountTypeA/AccountTypeB serializers in included_serializers.
extract_included expects both fields to be present on every account instance when in reality each account will have either the A or B relation. This pull request makes extract_included to ignore missing fields.
=> Included field might not be set

docs/api.md, docs/usage.md, example/serializers.py, example/tests/integration/test_meta.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/unit/test_renderer_class_methods.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py
Solves #154.
By declaring a `meta_fields` property on the serializer's `Meta` class meta data can be added to the:
By declaring a `get_root_meta` function on a serializer data can be added to the:
``` js
{
"data": [
{
"type": "entry",
"id": "1",
"attributes": {
"title": "Test",
},
// set by EntrySerializer `meta_fields`
"meta": {
"bodyFormat": "text"
}
}
],
// set by the `get_root_meta` function on EntrySerializer
"meta": {
"bar": "Baz"
},
}
```
=> Added support for adding meta objects from serializers

example/models.py, example/serializers.py, example/tests/integration/test_model_resource_name.py, example/urls_test.py, example/views.py, rest_framework_json_api/relations.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py, rest_framework_json_api/views.py
I mentioned this yesterday on issue #74  and figured I would just open a PR to get opinions on this change. 
This would allow a `resource_name` to be specified on the model. This was required in certain cases (relations: [this line](https://github.com/django-json-api/django-rest-framework-json-api/blob/73bc6d57a1321ec4d831e2a78a1b09d1d6573308/rest_framework_json_api/relations.py#L121)) where no serializer or view could have overridden the resource_name. This would allow the `resource_name` of a model to be overridden globally for that model. 
I haven't written any tests yet as I uncovered a lot of places the model `__name__` property is used, hence WIP. 
EDIT:
Test  TODOs:
=> Added the ability to specify a resource_name on Models

example/tests/test_views.py, example/urls_test.py, rest_framework_json_api/parsers.py
Allow the deletion of relationships using the `relationships` values of a request, eg:
```JSON
{
"data": {
"id": 1,
"type": "model",
"attributes": {
"name": "test-model",
"number": 1
},
"relationships": {
"other-model": {"data": null}
}
}
}
```
See [JSON API specification](http://jsonapi.org/format/#crud-updating-to-one-relationships)
References  #169
=> Relationship deletion

docs/usage.md
=> Fix pagination configuration docs

example/tests/test_relations.py, rest_framework_json_api/relations.py
Previously, if a ResourceRelatedField was passed as input an invalid
resource identifier object missing either the 'type' or 'id' attributes,
this resulted in an uncaught KeyError and a 500 error. This commit
adds validation that the object contains both a 'type' and 'id' attribute.
It fails with a helpful error message.
=> ResourceRelatedField validation

docs/usage.md, example/serializers.py, example/tests/integration/test_model_resource_name.py, example/views.py, rest_framework_json_api/relations.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py, rest_framework_json_api/views.py
=> Use JSONAPIMeta in models to determine the resource name

rest_framework_json_api/exceptions.py
=> Fix potential circular import edge-case

example/tests/unit/test_pagination.py, rest_framework_json_api/pagination.py
While its not an official specification or requirement of the JSON API, DRF does provide support for limit/offset pagination and is widely used. So i think this might be an useful addition to this package, and can be used as optional paginator.
Limit and offset arguments are based on the pagination notes here: http://jsonapi.org/format/#fetching-pagination.
Examples:
http://api.example.org/accounts/?page[limit]=100
http://api.example.org/accounts/?page[offset]=400&page[limit]=100
I will write some unit test once one of the maintainers is oke with this going in.
=> Add LimitOffsetPagination

example/factories/__init__.py, example/serializers.py, example/tests/integration/test_includes.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, tox.ini
As reported in #200, include paths can be compound of many nodes.
When requesting a deeply nested node, all intermediate nodes must be included as well.
This PR is similar to #200 but involves less code base modifications and includes tests.
=> Support deeply nested includes

example/views.py, rest_framework_json_api/serializers.py
Maybe a bit too simplistic.  Wish I had an additional test to add, but then I might be overlapping django rest's tests for the `get_serializer_class` method.  Tests fail if view uses `serializer_class` rather than what is in this commit however.
This should now allow users to specify multiple actions and direct the query to different Serializers depending on the request action.
=> [FEATURE]: support using get_serializer_class on view

example/tests/unit/test_utils.py, rest_framework_json_api/utils.py
Fixed get_resource_name in case of non-model backed serializer. Seems that `getattr` evaluates the default regardless of whether the default case is used ([Similar SO Question](http://stackoverflow.com/questions/31443989/python-getattr-with-another-attribute-as-the-default)). For serializers without a `meta.Model` this poses a problem. 
Closes #219
=> Fixed get_resource_name in case of non-model backed serializer.

.gitignore, docs/api.md, docs/usage.md, example/serializers.py, example/tests/integration/test_meta.py, example/tests/unit/test_renderer_class_methods.py, rest_framework_json_api/renderers.py
Uses tests from #179 and fixes #198
=> fixed get_root_meta for lists

example/serializers.py, example/tests/integration/test_includes.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, rest_framework_json_api/relations.py
Replaces #151. Fixes #220.
I'd like some review and it'd be great if you could pull this into your project and give it a test drive.
=> Support many=True on related serializer method fields.

example/tests/test_views.py, example/views.py, rest_framework_json_api/exceptions.py, rest_framework_json_api/utils.py
This makes it easier to haver DRF-jsonapi alongside normal DRF API. Aside of config you can already set on class, like for example:
```python
class DRFJsonApiConfigurationMixin:
paginator_class = rest_framework_json_api.pagination.PageNumberPagination
parser_classes = [
rest_framework_json_api.parsers.JSONParser,
rest_framework.parsers.FormParser,
rest_framework.parsers.MultiPartParser,
]
renderer_classes = [
rest_framework_json_api.renderers.JSONRenderer,
rest_framework.renderers.BrowsableAPIRenderer,
]
metadata_class = rest_framework_json_api.metadata.JSONAPIMetadata
paginate_by = 10
paginate_by_param = 'page_size'
max_paginate_by = 100
```
exception handler can't be set that way. To get properly formatted error response the views **handle_exception** must be overridden. The …
=> Correct error responses for projects with different DRF-configurations

rest_framework_json_api/exceptions.py, rest_framework_json_api/renderers.py, rest_framework_json_api/utils.py
This fixes #218 and also addresses #214.
If the optional `JSON_API_UNIFORM_EXCEPTIONS` is set to `True`, *all* exceptions will respond with the JSON API format. This is how it used to work, but now for non-JSON-API views, the top-level `errors` object is properly included in the response, fixing #218.
When `JSON_API_UNIFORM_EXCEPTIONS` is `False` (the default), non-JSON-API views will respond with the normal DRF error format, addressing #218 in a way that doesn't require views to manually override `handle_exception` (which is how it was addressed in #222).
=> Allow exception handler to be used by normal DRF views

example/tests/integration/test_model_resource_name.py, rest_framework_json_api/renderers.py
When setting `resource_name = None`, the related instance's resource
name is used in `relationships`, but `None` is used in `included`.
This is related to
#94
and #124
=> Fix resource name inconsistency between `included` and `relationships`

rest_framework_json_api/utils.py
Currently, `fields = ()` in a serializer doesn't work because `get_serializer_fields` returns `None`
=> Let serializers have empty field lists

example/tests/integration/test_includes.py, requirements-development.txt, rest_framework_json_api/renderers.py, rest_framework_json_api/utils.py
Let's provide an extra `JSONAPIMeta` configuration option that specifies
**resources** to be listed in the '`included`' section of the response.
These resources shall be included even if they're not explicitly mentioned
in the 'include' request parameter.
=> Add option to specify default included resources

rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py
In [parsers](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/parsers.py#L32), we convert incoming keys to snake case (undoing whatever formatting was done during [rendering](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L66)). However, include parameters have to exactly match the fields of models/serializers.
This PR brings the same reversal behavior to include parameters as its done for attributes, etc.
Example:
`?include[firstName]=` == `?include[first_name]=`
=> Convert include queries back to snake case

.gitignore, rest_framework_json_api/renderers.py, rest_framework_json_api/utils.py
Hi, seems @adaptivdesign is on vacation, so to speed things up, I've resolved the conflicts in his PR #253. You can merge this PR instead. Thanks.
=> Rebased PR#253 open by adaptivdesign

docs/api.md, docs/usage.md, example/tests/test_parsers.py, rest_framework_json_api/parsers.py
The JSONParser will add metadata in the request under a top level key `_meta`.
This provides access to the data in the `meta` tag of the request.
=> Include metadata in JSONParser output

example/serializers.py, example/tests/integration/test_includes.py, rest_framework_json_api/renderers.py
When using a `SerializerMethodResourceRelatedField` in a serializer, with `many=True` being set, and the request is asking for to include it (via the `?include`) parameter, the field is not included in the result.
This PR adds a test and a fairly hackish fix (by checking is a 'child_relation' is present in the `_kwargs` parameter, when the field is evaluated for includes).
=> SerializerMethodResourceRelatedField with many=True does not show up in included

.gitignore, .travis.yml, setup.cfg, setup.py
Isort & flake8 rules for contributors using these tools in their editor.
Also pinned pytest version, to get tests to pass. (pytest-factoryboy doesn't yet support pytest3+).
=> Add isort & flake8 settings.

requirements-development.txt
On 2.8.2 the tests didn't run for me (Python 3.5.2). I got this exception:
```
pkg_resources.VersionConflict: (pytest 2.8.2 (/Users/amw/.virtualenvs/jsonapi/lib/python3.5/site-packages), Requirement.parse('pytest>=2.9'))
```
This PR upgrades py.test to 2.9.2 which worked great on a clean virtualenv with python 3.5.2.
On pytest 3.x tests seem to be failing at the moment.
=> Upgrade py.test to 2.9.2.

rest_framework_json_api/parsers.py
Currently the parser always sets `request.data['id']` even for POST requests that often don't include it. This doesn't play well with some serializer options like `default`. If `id` is part of `serializer.initial_data` then it will not be replaced by the field's default value even if it is `None`.
=> Don't set `id` to None when it's not submitted with the request

example/tests/unit/test_renderers.py, rest_framework_json_api/renderers.py
Closes issue #270
I added a renderer unit test to catch this error. 
Unfortunately the bug only occurred when there was a single relation on the serializer so I had to make some simplified serializers to reproduce the issue.
=> Remove check for relation_instance as it was not available in scope

example/serializers.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/urls_test.py, rest_framework_json_api/relations.py
Added `self` and `related` links to `SerializerMethodResourceRelatedField`
=> Serializermethod links

example/tests/test_views.py, rest_framework_json_api/renderers.py
That special case for RelationshipView needs to happen after we checked for errors otherwise they will be treated like a regular list data.
=> Fix errors in relationship views

example/tests/unit/test_renderer_class_methods.py, rest_framework_json_api/renderers.py
Remove all hardcoded calls to JSONRenderer methods and change all staticmethods to classmethods in rederers.py so they can be safely overriden.
=> Fix #299 (change JSONRenderer staticmethods to classmethods)

example/tests/test_parsers.py, rest_framework_json_api/parsers.py
Currently the parser fails with "AttributeError: 'list' object has no attribute 'get'" when the passed JSON is not a dictionary. This causes Server Error (500) response.
The diff looks big, but I've just added the type check and moved the error from the bottom to the beginning. The rest is the same code but unindented.
=> Gracefully handle no data

example/tests/integration/test_meta.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/test_format_keys.py, example/tests/test_generic_validation.py, example/tests/test_generic_viewset.py, example/tests/test_model_viewsets.py, example/tests/test_serializers.py, example/tests/utils.py
Pytest gives cleaner output if you compare list/dictionaries instead of dumped jsons. It is also easier to read tests.
=> Refactor tests.

docs/usage.md, requirements-development.txt
This branch adds documentation for how to include extra resources
under the `included` key.
It also adds Sphinx and the extra required dependencies to build
the docs to `requirements-development.txt`.
I wrote this from the perspective of a user who recently encountered the need to side load extra data and had to scour the source to find it. If it's lacking in additional features that are hidden, I'd love to know and would be happy to add more.
=> Document DJA's ability to use Compound Documents.

example/tests/test_views.py, rest_framework_json_api/views.py
The app crash with error: `TypeError: add() got an unexpected keyword argument 'bulk'`, when trying to patch many-to-many relationships. In file `example/tests/test_views.py` was added the test catching this error. It's error is possible only in Django >= 1.9, because was added the `bulk` argument in `add()` method for all `Manager` classes, excluding `ManyRelatedManager` class. In file `rest_framework_json_api/views.py` was added check the class name to fix this error.
=> Fixed crash when patching many-to-many relationships in Django >= 1.9

rest_framework_json_api/metadata.py
On relation fields line 131 is getting all the related objects.
=> Avoid choices evaluation on relational fields getting field metadata

example/tests/test_views.py, rest_framework_json_api/renderers.py
Closes #339 
I found this bug while testing an API, and making request with the `fetch` client provided by React-Native. 
This is my first approach to fix the bug. Maybe there is a better way.
=> Fix JSONRenderer when status_code is `204 NO CONTENT`

AUTHORS, CHANGELOG.md, rest_framework_json_api/parsers.py
This attribute key translation was advertised to be "off by default", but was in fact forced in parser. This commit makes it so that request attributes and relations are only translated back to snake_case format if JSON_API_FORMAT_KEYS setting is set.
I'm not mad – I don't have my model/serializer attributes named someField or SomeField. My use case is quite simple: I have a JSONField where I accept some black-box content for storage. I need to be able to return the data as it was submitted to me by users of the API.
=> Don't force translation of request attribute names

CHANGELOG.md, rest_framework_json_api/utils.py
PR #319 brought support for generic relations. Unfortunately apps that don't add contenttypes to it's INSTALLED_APPS would crash and burn:
```
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```
I would like to add a test for this, but it would require two separate Django configs. Not sure how you would want to handle that in py.test.
Also using `type(something) is object()` comparison as a safer alternative to `type(something) is type(None)`. If `something` happened to be `None` we would enter a branch that was never supposed to run.
=> Fix for apps that don't load contenttypes module.

rest_framework_json_api/views.py
```
RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls
```
=> Fix Django deprecation warning

AUTHORS, example/serializers.py, rest_framework_json_api/serializers.py
=> Fix tests to work with DRF 3.6.3.

AUTHORS, example/tests/unit/test_pagination.py, rest_framework_json_api/pagination.py
We're working on a project using django-json-api and came across unintuitive behavior for the pagination. The current pagination implementation for the 'last' link is basically a 'total count' - 'limit'. Consider the following example:
Objects = [0-21]
Limit = 10
(first page - offset 0)
0,1,2,3,4,5,6,7,8,9
(clicking 'next' - offset 10)
10,11,12,13,14,15,16,17,18,19
(clicking 'next' - offset 20)
20,21
(clicking 'last' - offset 12)
12,13,14,15,16,17,18,19,20,21
This behavior would make the user completely disoriented in the paging. It makes more sense that 'last' will offset to 20 just the same as clicking 'next'->'next'->'next' and simply return two objects instead of 10.
=> Fix for pagination ‘last’ link to give the real last page

AUTHORS, example/models.py, example/serializers.py, example/tests/test_utils.py, rest_framework_json_api/utils.py
In case of reverse m2m relationships the wrong type was returned.
I created a test to reproduce this situation.
=> Fixes types in reverse m2m relationships

CHANGELOG.md, example/serializers.py, example/tests/integration/test_includes.py, example/tests/test_serializers.py, rest_framework_json_api/renderers.py
In ResourceRelatedField it is possible to rename/remap a field so it can be represented in the api with a different name using the source attribute. This works well however if I request to include this relationship in `included` it won't be returned.
I have added a test which should make it clearer what issue this PR addresses.
=> Added nested included serializer support for remapped relations

AUTHORS, rest_framework_json_api/renderers.py
fix https://github.com/django-json-api/django-rest-framework-json-api/issues/358
=> respect custom related_link_url_kwarg

docs/getting-started.md, example/requirements.txt, example/tests/integration/test_polymorphism.py, rest_framework_json_api/serializers.py
Some miscellaneous bugs, some of which stemmed from polymorphic. Fixes #356
=> [WIP] Fix example app

requirements-development.txt, setup.py
Factoy Boy 2.9.+ versions are raising this problem when we run the test suite using py.test
ConftestImportFailure: (local('/home/santiago/develop/invgate-django-rest-framework-json-api/example/tests/conftest.py'), (<type 'exceptions.AttributeError'>, AttributeError("'DjangoOptions' object has no attribute 'postgen_declarations'",), <traceback object at 0x7fb1c6b123b0>))
Related issue https://github.com/pytest-dev/pytest-factoryboy/issues/47
To fix this problem temporally  we can switch to FactoryBoy 2.8.1.
=> Fix factory boy dependency

requirements-development.txt
"mock" is included twice in the development requirements. This causes pip install to fail with 
```
Double requirement given: mock (from -r requirements-development.txt (line 15)) (already in mock (from -r requirements-development.txt (line 5)), name='mock')
```
=> removed duplicate requirement

rest_framework_json_api/utils.py
```
plan = PlanSerializer(source='subscription.plan')
```
`plan` is a field of another serializer which needs to be resolved using `obj.subscription.plan` property. It works for standard DRF JSON response but fails in drf-json-api.
This PR fixes that issue by replacing `getattr` with `operator.attrgetter` which is able to resolve  the sub-attr access.
=> Fix for resolving source when accessing sub-attr eg b.c

rest_framework_json_api/__init__.py, setup.py
The `six` library is required, but it was not included in the packaging.
Fixes #389
=> Add six as a dependency.

.travis.yml, AUTHORS, CHANGELOG.md, README.rst, docs/getting-started.md, rest_framework_json_api/__init__.py, rest_framework_json_api/relations.py, rest_framework_json_api/utils.py, rest_framework_json_api/views.py, setup.py, tox.ini
The effect of dropping support for Django 1.8 - 1.10 is pretty huge. Lots of test environments can go away.
Python 3.3 is EOL so I dropped that.
Django 1.8 - 1.10 are (basically) EOL so I dropped them.
Django REST Framework doesn't support Django 1.11 until a bug fix release of DRF 3.6.x so I dropped those too.
If the tests go green, I'll begin removing the old bits that are in the package files. 
Fixes #386
=> Drop support for Django 1.8 - 1.10

example/settings/dev.py, example/tests/conftest.py, example/tests/integration/test_includes.py, example/tests/integration/test_meta.py, example/tests/integration/test_model_resource_name.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/integration/test_polymorphism.py, example/tests/test_format_keys.py, example/tests/test_generic_validation.py, example/tests/test_generic_viewset.py, example/tests/test_model_viewsets.py, example/tests/test_serializers.py, example/tests/test_views.py, example/tests/utils.py, example/urls_test.py, example/views.py, rest_framework_json_api/renderers.py, rest_framework_json_api/utils.py
This allows to define json api format as default in tests. Following needs to be configured:
```python
REST_FRAMEWORK {
...
'TEST_REQUEST_RENDERER_CLASSES': (
'rest_framework_json_api.renderers.JSONRenderer',
),
'TEST_REQUEST_DEFAULT_FORMAT': 'vnd.api+json'
...
}
```
With this change tests can be simplified and there is no need to specifically assign json api content type and dump resp. load data as json. This PR changes tests accordingly.
More detail documentation on this rest framework feature can be found [here](http://www.django-rest-framework.org/api-guide/testing/#configuration)
=> Allow json api renderer to be used as test request renderer class

AUTHORS, rest_framework_json_api/renderers.py
As requested by @mblayman in #372, I am raising an additional pull request, including the changes from #372, to fix the remaining issues that where blocking this from being merged.
I have also rebased my branch against the master branch as I was advised that development has now moved from develop to master.
=> Polymorphic list fixes

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, example/models.py, example/tests/integration/test_includes.py, example/tests/integration/test_meta.py, example/tests/integration/test_model_resource_name.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/integration/test_polymorphism.py, example/tests/integration/test_sparse_fieldsets.py, example/tests/test_format_keys.py, example/tests/test_generic_validation.py, example/tests/test_generic_viewset.py, example/tests/test_model_viewsets.py, example/tests/test_multiple_id_mixin.py, example/tests/test_serializers.py, example/tests/test_sideload_resources.py, requirements-development.txt, setup.py, tox.ini
=> Add DRF 3.7 and Django 2.0 to the test matrix.

.travis.yml, requirements-development.txt, setup.py
PR #407 is failing CI currently because of a package version issue and the PR is only changing a typo in the usage file. Some dependency requirement must have changed recently.
I'm trying this PR to see if it's now possible to have factory-boy working on a newer version.
=> Remove factory-boy version constraint.

rest_framework_json_api/exceptions.py, rest_framework_json_api/renderers.py
I've hit a nasty performance issue with one of my index-type API endpoints. It returns only about 600 elements each with 3 additional resources included (one of them nested under another). The included resources are widely shared (loaded with `prefetch_related`). All database queries for this request taken together execute for less than 10ms, but the entire request takes over 2 seconds to complete. That's not reasonable at all.
Turns out main view code was taking *"only"* about 500ms (still a lot for this amount of data) while `JSONRenderer.render` was taking almost 2 seconds.
In this PR I am introducing some optimizations to `JSONRenderer.extract_included` – instead of serializing all related resources and then deduplicating them near the end, I pass a cache of serialized resources and …
=> Speed up JSONRenderer.extract_included

LICENSE, docs/CONTRIBUTING.md, docs/conf.py, docs/index.rst, requirements-development.txt
This branch adds a skeleton of contribution guidelines and cleans up
little bits that I noticed along the way.
For #424
=> Add a CONTRIBUTING.md file.

example/tests/test_generic_viewset.py, example/tests/test_model_viewsets.py, example/tests/unit/test_settings.py, example/tests/unit/test_utils.py, rest_framework_json_api/exceptions.py, rest_framework_json_api/parsers.py, rest_framework_json_api/settings.py, rest_framework_json_api/utils.py
This is inspired by api_settings of REST framework.
Advantages:
* Centralizing all json api settings and defaults in one module
* Simplifying refactoring and deprecation of settings in the future
* Properly use override_settings in tests instead of monkey patching
=> Add json api settings module

docs/usage.md, example/tests/test_relations.py, rest_framework_json_api/mixins.py, rest_framework_json_api/relations.py
As documented in http://www.django-rest-framework.org/api-guide/relations/#custom-relational-fields this allows to implement custom `ResourceRelatedField` where queryset is depended on context.
=> Allow overwriting of get_queryset() of related field

.gitignore, .travis.yml, setup.cfg, setup.py, tox.ini
This way we can harmonize tox and travis configuration
Fixes #391
=> Use tox to run test in travis

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, tox.ini
=> Add support for Django REST Framework 3.8.x

CHANGELOG.md, rest_framework_json_api/__init__.py
It's time again for another release as quite a few important fixes/changes have been added.
@mblayman 
This will be the first release I will make. You have already documented concerning twine. I assume I do not have pypi rights for this project yet though?
Also another question how do we update Read The Docs?
Thanks for your feedback.
=> Release 2.5.0

CHANGELOG.md, README.rst, docs/usage.md, example/settings/dev.py
Partially addresses #432
Improve `REST_FRAMEWORK` settings recommendation including:
* Testing configuration as explained [here](http://www.django-rest-framework.org/api-guide/testing/#configuration)
* Sorting configuration according to [json api spec](http://jsonapi.org/format/#fetching-sorting)
=> Improve REST_FRAMEWORK settings recommendation

README.rst
Add goals of Django RESTFramework JSON API which we can reference to and use as basis in discussions of issues and pull requests.
This goals are extracted from following [comment](https://github.com/django-json-api/django-rest-framework-json-api/issues/155#issuecomment-301172555) made by @mblayman. I can fully agree to those points and think it is important to document those goals in a easy to find place.
=> Document goals of Django REST Framework JSON API

CHANGELOG.md, README.rst, docs/usage.md, rest_framework_json_api/pagination.py
* Add additional hyperlinks
* Convert http links to https where applicable
Currently we have a mix of Markdown and reStructered Text in our documentation. In the future we should consider focusing on one Markup language.
=> Update documentation hyperlinks

CHANGELOG.md, docs/usage.md, example/serializers.py, example/tests/test_views.py, example/urls.py, example/urls_test.py, example/views.py, rest_framework_json_api/relations.py, rest_framework_json_api/views.py
Fixes #450 
Fixes #426
Add `RelatedMixin`. This introduces new approach in handling related urls/entities. `RelatedMixin` will handle all related entities, configured in `related_serializers` dict with no related views required. Also it will check permissions for parent object for any related entity.
=> Add support for related links using parent view and its permissions

docs/getting-started.md
Fixes #454
Minor documentation correction
=> Issue 454: Documentation correction

CHANGELOG.md, README.rst, docs/usage.md, example/tests/unit/test_pagination.py, example/views.py, rest_framework_json_api/pagination.py
Per a [discussion](https://github.com/django-json-api/django-rest-framework-json-api/pull/455#pullrequestreview-144719067) with @sliverc, renamed recently-added pagination classes from `JsonApi`-prefix to `JSONAPI`-prefix. This includes new deprecation warnings for the old names.
I also added a minor fix to tox.ini not to run flake8 on the entire directory but only the relevant files.
You can cherry-pick that out if you prefer it not to be part of this PR.
(This replaces #458 where I messed up the history by rebasing incorrectly.)
=> JSONAPI prefix for paginators

README.rst, docs/usage.md, example/settings/dev.py, rest_framework_json_api/filters/__init__.py, rest_framework_json_api/filters/sort.py
Fixes #471
Remove "JSONAPI" prefix from `OrderingFilter` before it is released.
No CHANGELOG.md changes needed as it's covered by "Add optional [jsonapi-style](http://jsonapi.org/format/) filter backends. See [usage docs](docs/usage.md#filter-backends)"
=> renamed JSONAPIOrderingFilter to OrderingFilter

README.rst, docs/usage.md, example/settings/dev.py, example/tests/test_filters.py, example/views.py
Fixes #432 
Documents how to use `rest_framework.filters.SearchFilter` along with the other filter backends.
Includes updates to the example app to demonstrate usage and test cases.
CHANGELOG.md remains unchanged because this is included in: "Add optional [jsonapi-style](http://jsonapi.org/format/) filter backends"
I also documented some `filterset_fields` to complement the `search_fields` in the usage document showing how to configure filter backends.
=> Document how to use `rest_framework.filters.SearchFilter`

CHANGELOG.md, README.rst, rest_framework_json_api/mixins.py
Fixes #480 
Deprecates `MultipleIDMixin` now that there's a JSON:API spec-compliant version (#466) using
`filter[id.in]=` instead of `ids[]=`. This will require **client changes** to change the query param.
=> deprecate MultipleIDMixin

CHANGELOG.md, rest_framework_json_api/__init__.py
Additional some small clarification of changelog.
@n2ygk 
I think we are ready for a new release. In case something is missing let me know.
=> Release 2.6.0

example/requirements.txt, example/serializers.py, requirements-development.txt, setup.py
DRF 3.3 is not supported anymore since DJA version 2.4.0
Deliberately left out CHANGELOG entry as this is only a internal change and not relevant to DJA user.
=> Remove obsolete packaging dependency

.travis.yml, README.rst, example/views.py, requirements-development.txt, rest_framework_json_api/django_filters/backends.py, setup.cfg, tox.ini
Fixes #460
This combines flak8 and isort environment and simplifies flake8 and isort tests for developers.
Deliberately left out CHANGELOG entry as this change is only of interest to contributors and not to users of DJA.
=> Use flake8-isort to check isort

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, tox.ini
Fixes #486 
Add test matrix entries for drf3.9 and drf master branch (so we can get an early look at 3.10+).
=> add drf39 and drfmaster tests

requirements-development.txt, rest_framework_json_api/relations.py, setup.cfg
As we do not have pinned dependencies linting broke as of automatic update to 3.6.0.
Pinned flake8 version and fixed linting.
=> Adjust to new flake8 3.6.0 version

README.rst
py.test is the old way of running pytest.
Also remove DJANGO_SETTINGS_MODULE env when running tests. This is already defined in pytest.ini and py.test will take it from as it should also take parameters we might add in pytest.ini in the future.
I have overlooked this change in #498
=> Use pytest instead of py.test

.pyup.yml
This way CI doesn't suddenly break when a dependency has updated (e.g. #501) but we still keep up-to-date.
pyupio will open a PR with the updated dependencies once they are released.
=> Use pyupio to manage development dependencies

example/settings/test.py, rest_framework_json_api/utils.py
Changelog entry was correct so not adding a new one which would only add noise.
=> Adjust warning to state to move to JSON_API_FORMAT_FIELD_NAMES

example/serializers.py, example/tests/unit/test_default_drf_serializers.py, example/urls_test.py, example/views.py
=> Test support of DRF HyperlinkedIdentityField

CHANGELOG.md, example/serializers.py, example/tests/test_views.py, rest_framework_json_api/views.py
Fixes #489 
Fixes raising of error when retrieving relationship which is referenced as `ForeignKey`on parent
=> Avoid error with related urls when retrieving relationship

AUTHORS, CHANGELOG.md, example/tests/unit/test_renderers.py, rest_framework_json_api/renderers.py
Fixes #421 
Don't output key for write only relations.
This builds on top of #421 and adds the requested test cases.
=> Don't render write only relations

CHANGELOG.md, example/tests/unit/test_renderers.py, rest_framework_json_api/renderers.py
Fixes #488
In case of a reverse one-to-one relationships `get_relation_instance` would swallow `DoesNotExist` exception leading renderer to skip field. Such field instead should be rendered as `null` and never be skipped.
=> Do not skip empty one-to-one relationships

example/api/resources/identity.py, example/settings/dev.py, example/tests/integration/test_includes.py, example/tests/integration/test_meta.py, example/tests/integration/test_pagination.py, example/tests/integration/test_polymorphism.py, example/tests/test_format_keys.py, example/tests/test_model_viewsets.py, example/tests/test_multiple_id_mixin.py, example/tests/test_parsers.py, example/tests/test_performance.py, example/tests/unit/test_default_drf_serializers.py, example/tests/unit/test_renderers.py, example/tests/unit/test_utils.py, example/views.py, pytest.ini
* Change to non deprecation pagination class per default
* filterwarnings per test level where a warning is actually tested
* Add some global filterwarnings for warnings which happen during import
time. (those can be removed resp. moved to specific test when tests are being restructured)
All in all this change helps output not being bloated with warnings when running tests.
=> Avoid deprecation warnings during tests

AUTHORS, CHANGELOG.md, example/models.py, example/serializers.py, example/settings/test.py, example/tests/test_views.py, rest_framework_json_api/views.py
Fixes #521
The details in #521 are not clear, but I ran into a very similar `SkipField` issue when trying to use HyperlinkedRelatedFields and the RelatedMixin. The HyperlinkedRelatedField generates the correct url for the related link (e.g. /authors/1/entries), but visiting the url gives a 500 error because of an unhandled `SkipField` exception. In other words, without these changes, it is possible to give a related link in the payload, but that link won't actually work.
=> Allow HyperlinkedRelatedField to be used with related urls

AUTHORS, CHANGELOG.md, example/tests/test_views.py, example/tests/unit/test_default_drf_serializers.py
Fixes #539 
Replaced the hardcoded year 2018 with `datetime.now().year` in all four tests which failed.
=> Removed hardcoded year 2018 from tests (#539)

CHANGELOG.md, example/tests/conftest.py, example/tests/integration/test_includes.py, rest_framework_json_api/renderers.py
Fixes #524 
The resource(s) in the data field of the response are removed from the included_cache before building the included field for the response.
I added an integration test which checks whether this works on a single comment. If I request a comment and ask for all the comments of its associated blog entry with `?include=entry.comments` all comments except the one which I requested should turn up in the included field.
=> Remove requested resources from included field

example/factories.py, example/serializers.py, example/tests/conftest.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/test_serializers.py, example/tests/unit/test_default_drf_serializers.py, example/tests/unit/test_renderer_class_methods.py, setup.cfg
A next step to clean up coverage.
=> Mark or remove uncovered example code

CHANGELOG.md, rest_framework_json_api/__init__.py
A few fixes have been implemented since the last version so I think it would be good to do another release.
=> Release version 2.7.0

AUTHORS, CHANGELOG.md, example/serializers.py, example/tests/integration/test_polymorphism.py, rest_framework_json_api/renderers.py
It is a very weird error I hit. We are using the DRF-JSONAPI to build 
https://github.com/occrp/id-backend
One of the packages we use is [django-simple-activity](https://github.com/richardARPANET/django-simple-activity). Where this package provides a model with a polymorphic relationship which we renamed in our project based on the relationship type:
https://github.com/occrp/id-backend/blob/master/api_v3/serializers/action.py#L55-L62
I get a strange error [when I try to include dynamically](https://github.com/occrp/id-backend/blob/master/api_v3/tests/views/test_activities.py#L55-L78) in the payload the renamed relationships.
I tracked down the error here:
https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/renderers.py#L356
I was not able …
=> Avoid exception when trying to include skipped relationship

AUTHORS, docs/usage.md
Fixes #
- [n/a] unit-test added
- [n/a] `CHANGELOG.md` updated (only for user relevant changes)
=> Clarify docs on controlling compound documents

CHANGELOG.md, example/tests/test_filters.py, rest_framework_json_api/django_filters/backends.py
It looks like `DjangoFilterBackend.get_filterset_kwargs` reused the same dictionary for the original (`filter[something]`) keys, the converted (`something`) keys, and the extra params (`include` or `page`).  By calling `data[key] = val` in while iterating `data.items()`, the indexes can be incorrectly changed: https://stackoverflow.com/questions/6777485/modifying-a-python-dict-while-iterating-over-it
With the path: `/api/products?filter[organization]=44cbbad6-d418-4129-8093-731637d5013b&filter[archived]=False&filter[productType.key]=biomass&include=images,product_type`, different filter params were ignored based on their order in the param string.
- `filter[productType.key]=...&filter[organization]=...&filter[archived]=False&include=images,product_type` 
- ignores `filter[archived]`
- …
=> DjangoFilterBackend.get_filterset_kwargs doesn't modify data dict while iterating

rest_framework_json_api/serializers.py
Fixes #629 
`import six` since it's no longer in DRF as of 3.10.
- [x ] PR only contains one change (considered splitting up PR)
- [ x] author name in `AUTHORS`
=> import missing six

CHANGELOG.md, rest_framework_json_api/compat.py, rest_framework_json_api/relations.py, rest_framework_json_api/renderers.py, rest_framework_json_api/views.py
Fixes #613 
* Fix `DeprecationWarning` over usage of `collections` instead of `collections.abc`
The PR doesn't seem to have user impacting changes. Let me know if these need to be updated.
Thanks.
=> Fix deprecation warnings regarding collections.abc

setup.py
Pin django debug toolbar to fix tests in master.
This is a quick fix and at a later point we should try to avoid having debug toolbar as dependency for tests. A bit more complicated to fix as example and tests are combined.
=> Pin django-debug-toolbar version to fix Python 2.7 tests

docs/conf.py
Fixes #636 
This fixes failing readthedocs build
=> Adjust building of apidoc to new sphinx version

CHANGELOG.md, example/tests/test_views.py, rest_framework_json_api/serializers.py
Fixes #315
Remove test for 'instance' from `__init__()` so that a call to get the RelationshipSerializer without an instance can be used by DRF's generateschema (3.10 milestone WIP). Missing values of `instance` (if there are ever any) will lead to an exception in `to_representation()`. There are no negative test cases that currently check for this.  The JSONAPI openapi schema generator (WIP; not yet submitted here) "knows" that the openapi schema for a[ Resource Identifier](https://jsonapi.org/format/#document-resource-object-identification) is just `type` and `id` strings so doesn't actually need to serialize it.
=> Allow OPTIONS request to be used on RelationshipView

tox.ini
=> Add missing envlist for Django 2.2 support

example/fixtures/blogentry.json, example/settings/dev.py
* admin app would need several middlewares and other apps configured, hence removed for example app
* Remove invalid authors references in blogentry.json
=> Allow example app and tests to be run with Django 2.2

CHANGELOG.md, docs/usage.md, example/tests/test_performance.py, example/views.py, rest_framework_json_api/views.py
Fixes #591
This PR adds  `SelectAndPrefetchForIncludesMixin` which handles `include` GET parameter and adds `select_related` and/or `prefetch_related` calls to queryset in order to save some sql queries.
This also deprecates `PrefetchForIncludesHelperMixin`.
`AutoPrefetchMixin` is modified so if developer declared `prefetch_for_includes` that means that it's handled "manually" and no need to auto prefetch related entities. 
Let's say we have a code like below:
```python
class Product(models.Model):
name = CharField()
tags = M2MField()
variant = FKField()
class ProductSerializer():
tags = ResourceRelatedField()
class VariantSerializer():
product = ResourceRelatedField()
class VariantViewset():
serializer_class = VariantSerializer
prefetch_for_include = {
'product': 'product__tags'
}
``` …
=> Allow defining of `select_related` per include

example/serializers.py, example/tests/test_views.py, example/views.py, rest_framework_json_api/django_filters/backends.py, setup.cfg
Updates setup.cfg to ignore the `.venv/` or `env/` directories as was already the case in `.gitconfig`.
This allows having a local virtualenv that `tox -e flake8` doesn't scan.
=> tox flake8-isort exclude env and .venv

CHANGELOG.md, example/tests/test_performance.py, example/views.py, rest_framework_json_api/views.py
Addresses testing issue in https://github.com/django-json-api/django-rest-framework-json-api/pull/643 
Polymorphic models do not always support [select_related](https://django-polymorphic.readthedocs.io/en/stable/advanced.html?highlight=select_related#about-queryset-methods) and might actually be [slower](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html?highlight=usage#performance-improvements).
Hence reverting change of `AutoPreloadMixin` as it has not been released yet.
=> Remove not always supported auto `select_related`

CHANGELOG.md, rest_framework_json_api/__init__.py
Last release before next major version 3.0.0.
=> Release version 2.8.0

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, example/api/resources/identity.py, example/models.py, example/requirements.txt, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/test_serializers.py, example/tests/unit/test_utils.py, example/views.py, pytest.ini, requirements-development.txt, rest_framework_json_api/compat.py, rest_framework_json_api/django_filters/backends.py, rest_framework_json_api/parsers.py, rest_framework_json_api/relations.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py, rest_framework_json_api/views.py, setup.py, tox.ini
Fixes #658
Fixes #659  
Following specific supports are removed:
* Python 2.7
* Python 3.4
* Django Filter 1.1
* Django REST Framework >=3.8
* Django 2.0
=> Drop support for obsolete dependencies

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, tox.ini
=> add tests for DRF 3.10

CHANGELOG.md, example/tests/test_model_viewsets.py, rest_framework_json_api/utils.py
Fixes the pointer for 404 results.
=> Avoid printing invalid pointer when api returns 404

example/api/resources/identity.py, example/tests/test_filters.py, example/tests/test_utils.py, example/tests/test_views.py
README suggest running flake8 before contributing, but current `master` reports issues.
```
$ flake8
./example/tests/test_views.py:14:1: I001 isort found an import in the wrong position
```
This fixes the current issue. Long term you'd probably want to add `flake8` to the test suite and reject PRs that have flake8 problems. If you don't care about `flake8` issues then maybe we should remove it from README?
=> Replace relative imports to make isort happy

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Deprecates DRF 3.9.  As of DJA 3.0 we'll only support DRF 3.10+.
=> deprecate DRF 3.9

CHANGELOG.md, example/tests/test_serializers.py, rest_framework_json_api/serializers.py
Fixes #683
Because of star import linting didn't realize that `ObjectDoesNotExist` exception was not properly imported.
=> Avoid exception when using `ResourceIdentifierObjectSerializer` with unexisting primary key

AUTHORS, CHANGELOG.md, example/tests/test_generic_validation.py, example/tests/test_generic_viewset.py, example/tests/test_model_viewsets.py, example/tests/test_views.py, rest_framework_json_api/utils.py
JSON:API specification allows for a `code` value in the [error object](https://jsonapi.org/format/#error-objects). This PR copies the `code` inside the `ErrorDetail` from rest_framework's `APIException` into the JSON:API error object. Allowing users of the library to send application-specific error codes back to the clients by specifying a code alongside the detail when raising an `APIException`
=> Add code to error object if `ErrorDetail` has code

docs/conf.py, rest_framework_json_api/renderers.py, rest_framework_json_api/views.py
Addresses all sphinx warnings.
=> Resolve sphinx documentation build warnings

requirements-development.txt, setup.py, tox.ini
pytest was already used when running test manually but not when running tox or travis. Partially addressing #635 
I want to keep the PRs small so for now removed twine dependency and django-filter resp. django-polymorphic dependency definition. Those will be reintroduced again later when introducing `extra_requires` and splitting up dependencies as in DRF.
=> Remove pytest runner to run test

CHANGELOG.md, example/tests/test_format_keys.py, rest_framework_json_api/metadata.py
Supersedes #500
Take into account setting JSON_API_FORMAT_FIELD_NAMES
=> Format metadata field names correctly for OPTIONS request

CHANGELOG.md, README.rst, docs/getting-started.md, docs/usage.md, setup.py
Fixes #674
Currently only django-filter and django-polymorphic use the extra_requires definition.
PR includes some small on the fly documentation changes.
=>  Use extra requires to separate optional features

CHANGELOG.md, example/tests/test_parsers.py, rest_framework_json_api/parsers.py
If you submit a list with one object, for example, drf_json_api will respond to you with unobvious errors.
=> Properly return parser error when primary data is of invalid type

CHANGELOG.md, example/tests/test_serializers.py, rest_framework_json_api/serializers.py
Fixes #759
As per issue #759 pass `self.instance` as the first parameter when initialising the child serializer from a polymorphic serialiser. This does not affect basic functionality, but makes the child serializer instance consistent with its usage of `instance` and `data`, which can fix potential issues when extending serilaizers that are part of a polymorphic serializer.
=> Pass on instance when using polymorphic serializers

CHANGELOG.md, rest_framework_json_api/__init__.py
Fixes #766 
Preparing next release 3.1.0
=> Release version 3.1.0

AUTHORS, CHANGELOG.md, docs/usage.md, example/serializers.py, example/tests/test_parsers.py, example/tests/test_relations.py, example/tests/test_serializers.py, example/tests/unit/test_serializer_method_field.py, rest_framework_json_api/relations.py
Fixes #639 - interface not consistent with `SerializerMethodField`
Fixes #779 - no enforcement of `read_only`
Fixes #780 - broken `parent` chain
=> Reimplement SerializerMethodResourceRelatedField

docs/usage.md
`FORMAT_KEYS` has been removed in version 3.0 and only
setting `JSON_API_FORMAT_FIELD_NAMES` is now available.
=> Replace old setting reference in documentation

AUTHORS, CHANGELOG.md, example/tests/test_views.py, rest_framework_json_api/views.py
Calling PATCH on an M2M RelationshipView when there were already some relationships was breaking. This was because the related objects were being deleted instead of just clearing the relationship and starting afresh.
Fixes #784
Fixes #244 
Manual testing proof:
=> Clear m2m relationships instead of deleting related objects during PATCH

AUTHORS, CHANGELOG.md, example/tests/test_views.py, rest_framework_json_api/views.py
Allow POST, PATCH, DELETE for actions in ReadOnlyModelViewSet (#797)
Currently if you try to use `POST` for action in `ReadOnlyModelViewSet` you will get problems:
- with DRF UI you will loose data input forms
- `drf_yasg` package will not generate OpenAPI specifications for such actions
This behavior was added to `django-rest-framework-json-api` in version 2.8.0 by mistake:
Commit: 7abd7649bff7116b8c23087b8fda3ea9b5bd38d6
Subject: remove disallowed PUT method. (#643)
=========================
@n2ygk, please review my PR because I'm changing your code from commit 7abd7649bff7116b8c23087b8fda3ea9b5bd38d6.
=> Allow POST, PATCH, DELETE for custom actions in ReadOnlyModelViewSet

setup.py
Fixes #803 
Avoid failling of master if we haven't added support for newly released versions yet.
=> Set maximum version of supported DRF and Django

example/serializers.py, example/settings/dev.py, example/tests/integration/test_meta.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/test_filters.py, example/tests/test_serializers.py, example/tests/test_views.py, example/tests/unit/test_default_drf_serializers.py, pytest.ini
Deprecation warnings should not be suppressed globally but instead test code be adjusted to new default behavior.
Cleanup of #776
=> Remove global ignore of serializer warnings

CHANGELOG.md, rest_framework_json_api/__init__.py
Fixes #814
Prepare release 3.2.0
=> Release version 3.2.0

README.rst, docs/getting-started.md, docs/usage.md, rest_framework_json_api/renderers.py
Fixes #818 
Correctly document JSON API ids as string
=> Correctly document JSON API ids as string

CHANGELOG.md
Fixes #821 
Clarify potential issue in changelog through introduction of `rest_framework_json_api.serializers.Serializer` class.
=> Clarify issue in changelog through introduction of new Serializer class

rest_framework_json_api/serializers.py
Fixes #433
Add api documentation to serializer classes and mixins.
=> Add api documentation to serializer classes

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Fixes #830
Drop support for end of life Django versions 1.11 and 2.1
=> Drop support for Django 1.11 and 2.1

README.rst, docs/getting-started.md
Currently whenever a Python, Django and Django REST framework series is end of life there is a conversation on when to drop it. I think for a user of DJA it is good to have this defined to avoid surprises.
Django REST framework does not really have an end of life definition (or have I overlooked this?) so supporting the last two series is feasible. In our upcoming release 4.0.0 we actually started supporting a new DRF release and dropping all lower DRF versions. Therefore a user is forced to update DJA and DRF at the same time.
I think it is fine for this round but should be avoided this in the future.
This PR should be the basis of discussion and can also be merged after the release of 4.0.0 whatever fits best.
=> Define what Python, Django and DRF series are supported

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Fixes #829
Drop [EOL](https://endoflife.date/python) Python 3.5 support
=> Drop EOL Python 3.5 support

CHANGELOG.md, example/tests/integration/test_sparse_fieldsets.py, rest_framework_json_api/serializers.py
Fixes #519
Stopped SparseFieldsetsMixin interpreting invalid fields query parameter
=> Stopped SparseFieldsetsMixin interpreting invalid fields parameter

.travis.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Fixes #841
Added support for Python 3.9
=> Added support for Python 3.9

AUTHORS, CHANGELOG.md, README.rst, docs/getting-started.md, docs/usage.md, example/serializers.py, example/settings/dev.py, example/templates/swagger-ui.html, example/tests/snapshots/snap_test_openapi.py, example/tests/test_format_keys.py, example/tests/test_openapi.py, example/tests/unit/test_filter_schema_params.py, example/urls.py, requirements/requirements-optionals.txt, rest_framework_json_api/django_filters/backends.py, rest_framework_json_api/schemas/openapi.py, setup.cfg, setup.py
Fixes #604
Fixes #644 
Extends DRF >= 3.12's generateschema to produce a jsonapi-formatted OAS schema document.
Builds on @n2ygk's work in https://github.com/django-json-api/django-rest-framework-json-api/pull/689
- Updated to latest DJA version
=> OAS 3.0 schema generation

CHANGELOG.md, rest_framework_json_api/__init__.py
Release new major version 4.0.0
=> Release version 4.0.0

pytest.ini, setup.cfg, tests/conftest.py
This is the basis to start migrating tests from example app.
=> Create tests module

AUTHORS, CHANGELOG.md, README.rst, docs/usage.md, example/settings/dev.py, example/tests/integration/test_browsable_api.py, rest_framework_json_api/renderers.py, rest_framework_json_api/templates/rest_framework_json_api/api.html, rest_framework_json_api/templates/rest_framework_json_api/includes.html
Fixes #851 
Add a `JSON:API includes` button to the browsable API view provided by DRF, allowing to select JSON:API includes to apply to the API call (applies to list and detail).
=> Feat: browsable renderer apply includes

AUTHORS, CHANGELOG.md, example/serializers.py, example/tests/snapshots/snap_test_openapi.py, example/tests/test_views.py, example/views.py, rest_framework_json_api/utils.py, rest_framework_json_api/views.py
Fixes #859 
Allows users to overwrite the `get_serializer()` and `get_serializer_class()` methods in subclassed views that have related or included serializers.
This change seems to interfere with OpenAPI Schema generation. As it stands, the tests `test_path_with_id_parameter` and `test_path_without_parameters` are failing, because the result no longer matches the expected snapshot. I suspect that the snapshots were incorrect in the first place, but I am not able to tell for sure.
- [o] unit-test added: I did not add a new unit test, but modified the test setup such that the problems became apparent in the existing test cases.
- [-] documentation updated
=> Allow users to overwrite `get_serializer_class` while using related urls

docs/usage.md
Fixes #865 
The following links in the documentation have been updated:
- "ordering filters" in the [Ordering Filters](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#orderingfilter) section: [old](http://django-rest-framework.readthedocs.io/en/latest/api-guide/filtering/#orderingfilter) -> [new](https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter).
- "SearchFilters" in the [Search Filter](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#searchfilter) section: [old](https://django-rest-framework.readthedocs.io/en/latest/api-guide/filtering/#searchfilter) -> [new](https://www.django-rest-framework.org/api-guide/filtering/#searchfilter).
=> Replace dead filter links in documentation

.pre-commit-config.yaml, README.rst, docs/CONTRIBUTING.md
Fixes #861
Add pre-commit for editor independent checking of linting and formatting of code before committing changes to git.
I have added a [pre-commit](https://pre-commit.com/#usage) configuration which uses the locally resp. in the virtual environment installed version of flake8, isort and black. pre-commit also has a way of handling the installation of such tools. However PyUp cannot update those version references and we might end up with different version in pre-commit and requirements.txt which we should avoid.  
The only down side to run tools locally is that a virtual env needs to be activated before committing. This needs to be the case anyway to run tests.
=> Introduce pre-commit to simplify contributions

CHANGELOG.md, rest_framework_json_api/utils.py, tests/test_utils.py
Fixes #704 
Fix issue preventing resolving the resource type of `ResourceRelatedField(many=True)` fields on plain serializers
- [n/a] documentation updated
=> Support many related fields on plain Serializers

example/tests/test_serializers.py
A test failed as it relied on a fix copyright year. Adjusted to calculate the year.
=> Calculate copyright date as it changes

AUTHORS, CHANGELOG.md, example/models.py, example/serializers.py, example/tests/integration/test_includes.py, example/tests/test_format_keys.py, example/tests/test_serializers.py, example/tests/unit/test_renderer_class_methods.py, rest_framework_json_api/renderers.py
When adding serializer as a field the meta fields are not rendered, This change provides the rendering capability, test and some fixes of related tests.
=> Render meta fields of included resource

example/settings/dev.py, example/tests/test_relations.py, tests/conftest.py, tests/serializers.py, tests/test_relations.py, tests/test_utils.py
Working in progress for #468 
Of test module `test_relations` for now only moved `ResourceRelatedField` related tests to keep the PR to a reasonable size.
=> Convert `ResourceRelatedField` test to pytest styled tests

CHANGELOG.md, rest_framework_json_api/__init__.py
=> Release 4.1.0

SECURITY.md, docs/CONTRIBUTING.md
We did not have any security issues in the past but there might be so I think it is important to have a security policy so users know how to report such with fully disclosing it in a GitHub issue. After all DJA exposes APIs which could be publicly exposed.
I've copied the policy from Django REST Framework and adjusted it. I recommend to read following [guide](https://github.com/google/oss-vulnerability-guide/blob/main/guide.md) which describes how security vulnerabilities are best addressed.
One question remains though is what means do we wanna use to privately communicate with us? Github has [Security Advisories](https://docs.github.com/en/github/managing-security-vulnerabilities/about-github-security-advisories) which I recommend we use. But only a admin can create security advisories. …
=> Create security policy

.github/workflows/tests.yml, AUTHORS, CHANGELOG.md, README.rst, docs/getting-started.md, setup.cfg, setup.py, tox.ini
Fixes #907
Allows the library to be used with Django 3.2.
I had to ignore a warning from Django related to django-debug-toolbar in order for tests to pass. I felt like that probably would be an acceptable way to work around it the deprecation warning without blocking this library to be upgraded to support Django 3.2, especially since the library doesn't depend directly on django-debug-toolbar.
=> Django 3.2 support

AUTHORS, CHANGELOG.md, example/tests/snapshots/snap_test_openapi.py, rest_framework_json_api/schemas/openapi.py
=> Support tags in OAS schema

CHANGELOG.md, docs/usage.md, example/tests/test_views.py, example/urls_test.py, rest_framework_json_api/views.py
Add logic to RelatedMixin (related views) and RelationshipView (relationship views) to make sure related field kwarg is properly converted to underscore format.
I don't have a test yet. Would appreciate some guidance on how to proceed. Basically I need to test the view action and make sure the related serializer is found based on the underscore-converted kwarg.
=> Properly support formatting of link segments in related urls

CHANGELOG.md, example/tests/test_performance.py, rest_framework_json_api/serializers.py, rest_framework_json_api/views.py
Pass the serializer to `select_related` and `prefetch_related` default `included_resources`. Without this, only resources specified by `?include` are used.
=> Prefetch default included resources

CHANGELOG.md, rest_framework_json_api/__init__.py
Fixes #911 
Prepare release 4.2.0
=> Release 4.2.0

SECURITY.md
Not sure how this happened but the DRF security email address was used instead of our newly created one.
=> Use correct security email address

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
My ideal would be that `Issues` is actually a list of work items with all the details for any contributor who wishes to work on it. All other discussion should happen in discussion. This follows the example of [DRF](https://github.com/encode/django-rest-framework/discussions/7740]
Adding issue templates will be one way forward into this direction to guide users how to report.
=> Added initial issue templates

CHANGELOG.md, example/serializers.py, example/tests/test_serializers.py, rest_framework_json_api/serializers.py
Fixes #949 
#900 inadvertently introduced validation of default included_resources which does not work properly with nested included resources (such as when a default included resources also defines its own included resources).
This PR reverts this validation but leaving the default prefetching of default included resources as intended in PR #900. 
This is a quick fix to get this regression solved. In the long run we need to think whether it makes sense at all to do validation of include in init of the serializer anyway. But can be discussed later.
=> Remove invalid validation of default included_resources

README.rst
A blank is needed for a list to be properly represented in RST
=> Resolved invalid example app browse to list in README

README.rst, docs/getting-started.md, docs/usage.md
This setting is now needed for browsable api and openapi schema. There might be more features coming needing this and it is also common practice to do this for django apps.
=> Documented how to add DJA to installed apps

AUTHORS, CHANGELOG.md, README.rst, SECURITY.md, docs/CONTRIBUTING.md, docs/conf.py, docs/getting-started.md, docs/index.rst, docs/usage.md, example/tests/test_filters.py, example/tests/test_generic_viewset.py, requirements.txt, rest_framework_json_api/django_filters/backends.py, rest_framework_json_api/exceptions.py, rest_framework_json_api/filters.py, rest_framework_json_api/pagination.py, rest_framework_json_api/parsers.py, rest_framework_json_api/renderers.py, rest_framework_json_api/schemas/openapi.py, rest_framework_json_api/serializers.py, rest_framework_json_api/settings.py, setup.py, tests/test_parsers.py
Fixes #940
Update JSON: API from JSON API in the docs. 
Test the updated docs at [Read the JSON: API](https://django-rest-framework-json-api-modify.readthedocs.io/en/docs-update/)
=> Unified usage of JSON:API abbreviation

AUTHORS, rest_framework_json_api/relations.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, rest_framework_json_api/settings.py, rest_framework_json_api/views.py
=> Clean up python2 related code crafts

MANIFEST.in
This was missed when introducing new tests folder. Removed obsolete exclude of pyc and pyo as there is already a global exclude with those extensions.
=> Added missing tests folder to MAINIFEST.in

CHANGELOG.md, README.rst, SECURITY.md, docs/CONTRIBUTING.md, docs/conf.py, docs/getting-started.md, docs/index.rst, rest_framework_json_api/settings.py
This follows the naming DRF uses in its own [documentation](https://www.django-rest-framework.org/) with an uppercase `REST` and all lowercase `framework`.
=> Use consistent naming for Django REST framework

docs/usage.md, example/views.py
Fixes #487
Make sure that in example app local queryset is used for filtering.
=> Align overwriting of get_queryset in example app and documentation

CHANGELOG.md, rest_framework_json_api/parsers.py, tests/test_parsers.py
Default parameter of `parser_context` was already set to `None` but would had always raised an error when it was actually `None`.
DRF parser allows `parser_context` to be `None` so this PR makes the DJA parser fully compatible with DRF API.
=> Allow parser context to be None

AUTHORS, CHANGELOG.md, README.rst, docs/Makefile, docs/getting-started.md, docs/make.bat, docs/usage.md, rest_framework_json_api/django_filters/backends.py, rest_framework_json_api/filters.py
Fixes #984
Changed all external links from `http://`  to `https://`.
=> Changed all external links to https

CHANGELOG.md, rest_framework_json_api/serializers.py, tests/test_serializers.py
Fixes #518
Fixes #710
This is to avoid an incomprehensible exception during runtime when either meta or results is used as a field name.
=> Check for reserved field names in serializer meta class

AUTHORS, CHANGELOG.md, example/tests/__snapshots__/test_openapi.ambr, rest_framework_json_api/schemas/openapi.py
Fixes #967
applied format_field_name to 3 instances of field.field_name and update snapshot
=> Resolved inflecting component attributes in OpenAPI SchemaGenerator

.github/workflows/tests.yml, tox.ini
* Moving from tox-gh-actions to tox-py (the same as DRF is already using)
* Move configuration what tests are allowed to fail into tox instead of GitHub settings
* Simplification of configuration as tox has the lead and no additional configuration is needed for actions.
=> Use one GitHub runner per Python version

CHANGELOG.md, README.rst, docs/getting-started.md, example/settings/dev.py, example/urls_test.py, requirements/requirements-optionals.txt, requirements/requirements-testing.txt, setup.cfg, setup.py, tests/test_relations.py, tox.ini
Fixes #1000 
Add support for Django 4.0 based on the first beta version (feature freeze already happened so this should be safe.)
=> Added support for Django 4.0

AUTHORS, CHANGELOG.md, rest_framework_json_api/utils.py, tests/test_utils.py
Partial fix of #1019
Enhanced the error message on get_resource type from serializer() to tell the user which serializer in which module is wrong configured.
=> Added missing error message when no resource name is configured on serializer

example/tests/integration/test_includes.py, example/tests/integration/test_polymorphism.py, example/tests/test_filters.py
Removes some old Python 2 literals
=> Executed pyupgrade with --py3-only

rest_framework_json_api/serializers.py, tests/test_serializers.py
Follow up of #992 
This check is for development purposes to verify that the source code is well configured but not needed during production. Therefore a assert is more appropriate.
=> Use assert when checking for reserved field names

CHANGELOG.md, rest_framework_json_api/__init__.py
New release with Django 4.0 support and more.
=> Release 4.3.0

CHANGELOG.md, README.rst, docs/getting-started.md, tox.ini
Removed end of life Django version 3.0 and 3.1.
=> Removed support for Django 3.0 and 3.1

example/urls.py
`django.urls.conf.url` is only there for Python 3.5 support which we already deleted anyway.
=> Updated urls to use path and re_path as is default in Django 2.2.

CHANGELOG.md, example/tests/integration/test_polymorphism.py, example/tests/test_serializers.py, example/tests/test_views.py, example/tests/unit/test_default_drf_serializers.py, rest_framework_json_api/django_filters/backends.py, rest_framework_json_api/filters.py, rest_framework_json_api/relations.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py
Since we dropped Python 3.5 support let's make use of the new f-string feature in Python 3.6+ for code improvement and readability.
=> Adjusted to only use f-strings for slight performance improvement

CHANGELOG.md, README.rst, docs/getting-started.md, requirements/requirements-testing.txt, setup.cfg, setup.py, tox.ini
Added support for Django REST framework 3.13
=> Added support for Django REST framework 3.13

CHANGELOG.md, setup.py
As planning for next major release bumping required version of inflection to next sensible one.
=> Set minimum required version of inflection to 0.5.0

CHANGELOG.md, README.rst, docs/getting-started.md, setup.py
Updated minimum required version of optional dependencies to releases which include most important bug fixes. Added documentation to highlight that we only actually test the latest versions of optional dependencies.
=> Update minimum required version of optional dependencies

.github/workflows/codeql-analysis.yml, docs/usage.md
This is now the standard naming of git repositories and Django has also moved to `main` naming.
What needs to be done besides this PR:
Add more TODOs in case I am missing anything.
For our local setup each of us will need to run the following:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> Rename primary branch from master to main

.github/workflows/tests.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Removing Python 3.6 support as it is [end of life](https://endoflife.date/python).
=> Removed support for Python 3.6

docs/requirements.txt
Flake8 and Spinx cannot be installed together anymore as of a conflict with importlib-metadata package.
As RTD only supports one requirements.txt file we need a separate one where only the dependencies for creation of documentation are installed.
This should solve this RTD [build error](https://readthedocs.org/projects/django-rest-framework-json-api/builds/16152993/).
=> Added requirements.txt for ReadTheDocs

example/tests/test_views.py, tests/test_views.py
Continuation of https://github.com/django-json-api/django-rest-framework-json-api/issues/468
Finally continuing convert some more tests to pytest style in the tests module.
=> Convert ReadOnlyModelViewSet to pytest style

CHANGELOG.md, example/tests/__snapshots__/test_errors.ambr, example/tests/test_errors.py, rest_framework_json_api/utils.py
Fixes #1069
- Add failing tests for misformed relationship pointers in error payloads
- Properly format relationship pointers in error payloads
- ~documentation updated~ N/A
- Dunno if relevant, only fixes an expected behavior and no-one complained so far…
=> Fixed invalid relationship pointer in error object

AUTHORS, CHANGELOG.md, rest_framework_json_api/utils.py, tests/models.py, tests/test_utils.py
Fixes #912 
I'm not sure if this specifically fixes the entirety of the first issue linked, I haven't had any problems with nested relationships that aren't M2M. However, this solves nesting for M2M on non declared fields. (Requires workaround for DRF in `ModelSerializer.build_field` to handle dotted field sources. Separate bug in that repo)
Slightly contrived example documenting equivalent structure to my local issue
```
class CourseSectionSerializer(ModelSerializer):
class Meta:
model = Student
fields = ("students",)  # M2M on "course" related field
extra_kwargs = {
"students": {"source": "course.students"}
}
```
Currently, this crashes on the line highlighted in the issue linked. It appears that somewhere along the line DRF updated how many relationships work and the previous `elif` …
=> Support many related field

CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Removed obsolete Django 2.2 support which is end of life since more than 3 months.
=> Removed support for Django 2.2

CHANGELOG.md, README.rst, docs/getting-started.md, example/tests/unit/test_default_drf_serializers.py, example/tests/unit/test_renderers.py, setup.cfg, setup.py, tox.ini
Added support for Django 4.1 which got released [recently](https://docs.djangoproject.com/en/4.1/releases/4.1/).
=> Added Django support for version 4.1.

CHANGELOG.md, docs/usage.md, rest_framework_json_api/utils.py, tests/test_utils.py
Fixes #399
Do not overwrite source.pointer field if it's already there; even if our pointer is calculated differently. Sorry for not updating the tests; tested it manually and it works for me and existing tests pass
=> Avoid overwriting of pointer when formatting error object

AUTHORS, CHANGELOG.md, rest_framework_json_api/parsers.py
This PR separates out the functionality of `parse` from `JSONParser` to a new `parse_data` method to allow parsing JSON data to the JSON:API specification directly, without passing a request byte stream directly. See #1079
=> Add a separate parse_data method to JSONParser

CHANGELOG.md, docs/usage.md
Fixes #1080 
Documents how to override the default DRF `generateschema` `--generator_class` with one that is DJA-specific.
=> Document how to override DRF generateschema generator_class.

tests/models.py
When calling makemigrations errors were raised as of conflict with related names. No test actually relied on this naming, so this PR cleans it up. I bumped into this when working on #1048 and could not create a migration without this change.
=> Avoided using same related name twice in tests models

CHANGELOG.md, README.rst, docs/getting-started.md, rest_framework_json_api/compat.py, rest_framework_json_api/metadata.py, rest_framework_json_api/schemas/openapi.py, setup.py, tox.ini
As per our policy, adding support for DRF 3.14 and dropping support for DRF 3.12 as we support the two last releases.
=> Added support for DRF 3.14 and dropping support for DRF 3.12.

.github/workflows/tests.yml, CHANGELOG.md, README.rst, docs/getting-started.md, example/tests/test_model_viewsets.py, setup.py, tox.ini
Added support for Python 3.11 which has been officially been [released](https://docs.python.org/release/3.11.0/whatsnew/changelog.html#python-3-11-0-final).
=> Added support for Python 3.11

docs/usage.md
Addresses #933
Added a clear policy that we encourage 3rdParty packages and a way to promote it as well in our documentation.
=> Added 3rdParty packages policy

CHANGELOG.md, rest_framework_json_api/schemas/openapi.py
This change makes the DJA schema class compatible with the DRF change introduced with https://github.com/encode/django-rest-framework/pull/7424
=> Added support to overwrite serializer methods in schema class

docs/usage.md
`resource_name` is not used in JSON:API spec.
Using “resource object identifier type” in the documentation makes it easier for newcomers to find this setting. Also clarified usage of `resource_name = False`, a question which occasionally has come up during discussions.
=> Clarified how to set resource object identifier type

example/settings/dev.py, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/integration/test_polymorphism.py, example/tests/test_filters.py, example/tests/test_views.py, example/views.py, requirements/requirements-codestyle.txt, rest_framework_json_api/django_filters/backends.py, rest_framework_json_api/exceptions.py, rest_framework_json_api/metadata.py, rest_framework_json_api/parsers.py, rest_framework_json_api/relations.py, rest_framework_json_api/schemas/openapi.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py, rest_framework_json_api/views.py, setup.cfg
Bugbear is a plugin for flake8 finding likely bugs and design problems. This PR adds it to DJA and already found some potential issues.
Also, it introduces an optional “line length too long” error which is more pragmatic than the E507 which we had disabled.
Currently, we disable line length altogether and leave it up to black to make it shorter. However, black does not format strings and comments etc. so some lines end up being very long. Bugbear will only flag lines which are longer than ~10% of the maximum length to solve this problem, but not to make the error becoming annoying.
=> Introduce flake8 bugbear plugin

SECURITY.md, docs/CONTRIBUTING.md
Finally, GitHub introduced a way to [report security vulnerability privately](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability). This makes the Google Group obsolete, which I found less than ideal, as it is just another system we need to use.
Adjusted security policy accordingly.
=> Adjusted security policy

.github/workflows/codeql-analysis.yml
Updated CodeQL to version 2 as v1 is going to be [deprecated](https://github.blog/changelog/2022-12-07-updated-timeline-for-the-deprecation-of-codeql-action-v1/)
=> Updated to CodeQL v2

.github/workflows/tests.yml, tox.ini
* Followed example of DRF using -f cmd line of tox v4 instead of tox-py
* For linting jobs updated to Python 3.8 as will be required by future updates of Flake8
* Added missing black job
=> Unified tox configuration

tox.ini
There is no need to install test dependencies when building docs.
=>  Removed unnecessary test dependencies when building docs 

AUTHORS, CHANGELOG.md, example/tests/__snapshots__/test_openapi.ambr, example/tests/unit/test_filter_schema_params.py, rest_framework_json_api/filters.py, rest_framework_json_api/schemas/openapi.py
Fixes #1120 
Refactored `sort` query parameter handling in order to avoid duplicate declarations in the generated schema for each endpoint.
=> Refactored sort query parameter handling in schema generation

.readthedocs.yaml
In Github Actions to test the docs we use Python 3.8 and Ubuntu 22.04 so we should do the same on RDT.
This fixes current [failing build](https://readthedocs.org/projects/django-rest-framework-json-api/builds/19548118/) (new Sphinx version needs Python 3.8)
=> Adjusted to use same Python and Ubuntu version for RDT

CHANGELOG.md, docs/conf.py, rest_framework_json_api/django_filters/backends.py, rest_framework_json_api/renderers.py, rest_framework_json_api/settings.py, rest_framework_json_api/utils.py
In version 5.0.0 this was already done but it seems some old formatted strings were still there.
=> Adjusted some still old formatted strings to f-strings

.readthedocs.yaml, docs/requirements.txt, tox.ini
docs/requirements.txt was only introduced as it was only possible to configure one “requirements.txt” in the web interface. In the yaml file it is possible to add several, therefore removing docs/requirements.txt.
Additionally, this should solve the still persistent build error, as the project itself also needs to be installed.
=> Made docs/requirements.txt obsolete and install project itself

CHANGELOG.md, rest_framework_json_api/metadata.py, rest_framework_json_api/pagination.py, rest_framework_json_api/relations.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py, rest_framework_json_api/views.py, tests/test_pagination.py
Fixes #1094
As Python 3.7+ now ensures that dicts are ordered, there is no need to use `OrderedDict` anymore.
See in-depth explanation at https://github.com/django-json-api/django-rest-framework-json-api/pull/1094#issuecomment-1438038120
Using regular dicts also make the code more readable and easier debuggable.
=> Replaced OrderedDict with dict

AUTHORS, CHANGELOG.md, example/api/serializers/identity.py, example/tests/test_generic_viewset.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py
Fixes #1136
Checks if a field matches [NON_FIELD_ERRORS_KEY](https://www.django-rest-framework.org/api-guide/settings/#non_field_errors_key) and sets the error pointer to `"/data"` if it does during DRF error formatting.
=> Use /data as the pointer for non-field serializer errors

example/tests/__snapshots__/test_openapi.ambr, example/tests/test_openapi.py, rest_framework_json_api/schemas/openapi.py
Fixes a schema issue introduced in 9ced3be23c5b5c7772d11959148e350300e382d0 that would result in broken YAML schema.
```yaml
components:
schemas:
error:
properties:
source:
properties:
pointer:
description: !!python/tuple
- A [JSON Pointer](https://tools.ietf.org/html/rfc6901) to the associated
entity in the request document [e.g. `/data` for a primary data object,
or `/data/attributes/title` for a specific attribute.
```
Only present on the main branch so I didn't update the changelog.
=> Revert SchemaGenerator description value from tuple to str

CHANGELOG.md, README.rst, docs/getting-started.md, example/settings/dev.py, setup.py, tox.ini
Allows library to be installed with Django 4.2.
This broadens the range of Django versions this library allows to be installed alongside to include Django 4.2 and any bugfix releases of it.
It also disables the use of the now deprecated `UnsaltedMD5PasswordHasher` hashing algorithm when running tests, as it otherwise would raise deprecation warnings. This will make the tests slightly slower since the default password hashing algorithm uses more resources, but it shouldn't have a big impact all in all as the tests run pretty quickly regardless.
=> Add support for Django 4.2

setup.cfg
Fixes #1145
This is to fix failing CI. Should actually be fixed in django-polymorphic where pkg_resources is [used](https://github.com/django-polymorphic/django-polymorphic/blob/master/polymorphic/__init__.py#L12).
Initially caused by an update of setuptools.
=> Ignored pkg_resources deprecation warnings

setup.py
In the last couple of new releases of Django and Django REST framework there were no real changes needed in DJA to work with those new versions. With the upper bound, we have currently set in our setup.py, our users need to wait for a new release to use a new Django or DRF version even though no changes are needed in DJA itself.
In #808 we introduced the upper bounds the main reason was to fix a documentation build, so a pipeline issue on our end and not an issue of a user as such.
The problem now is though that our users cannot use Django 4.2 with DJA as we are waiting for DRF to release a version for Django 4.2. (see #1142). As DRF does not have an upper bound though, users can easily use DRF with a new version but not DJA.
As of this, I recommend we remove the upper bound. We only …
=> Removed upper bounds of Django and DRF

CHANGELOG.md, example/tests/test_openapi.py, rest_framework_json_api/schemas/openapi.py
Omits the `#/components/parameters/include` reference from operation parameters if the given serializer does not implement `included_serializers`.
At least the documentation makes it seem that `included_serializers` is the only official way of adding include to the parameters, so I assume checking it like this would be safe.
=> Omit include parameter from OpenAPI schema when left unused

CHANGELOG.md, example/tests/test_openapi.py, rest_framework_json_api/schemas/openapi.py
Omits the "id" field from `/data/attributes` the OpenAPI schema, as the `JSONRenderer` [explicitly removes it from the attributes](https://github.com/django-json-api/django-rest-framework-json-api/blob/main/rest_framework_json_api/renderers.py#L61-L63).
```python
{
"type": "object",
"required": ["type", "id"],
"additionalProperties": False,
"properties": {
"type": {"$ref": "#/components/schemas/type"},
"id": {"$ref": "#/components/schemas/id"},
"links": { ... },
"attributes": {
"type": "object",
"properties": {
"id": {"type": "integer", "readOnly": True},  # <- Not real
"name": {"type": "string", "maxLength": 100},
},
"required": ["name"],
},
"relationships": { ... },
},
}
```
=> Omit id field from OpenAPI schema attributes

docs/usage.md
Fixes #1141
Adjusted invalid query regex documentation where type was missing for customizing QueryParameterValidationFilter.
=> Added missing group type to custom query parameter regex

CHANGELOG.md, example/tests/test_openapi.py, rest_framework_json_api/schemas/openapi.py
`SerializerMethodResourceRelatedField(many=True)` (`ManySerializerMethodResourceRelatedField`) fields would be documented in the OpenAPI schema with "#/components/schemas/reltoone" reference instead of "#/components/schemas/reltomany" reference.
=> Fix many serializer method fields having the incorrect relation schema

CHANGELOG.md, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/test_filters.py, rest_framework_json_api/renderers.py
Fixes #572
`SerializerMethodResourceRelatedField(many=True)` (`ManySerializerMethodResourceRelatedField`) fields are given a meta section with a count much like `ManyRelatedField`.
=> Include meta section for SerializerMethodResourceRelatedField(many=True)

CHANGELOG.md, example/tests/__snapshots__/test_openapi.ambr, rest_framework_json_api/schemas/openapi.py
Required relationships are added to the `required` array under `relationships` in the OpenAPI schema.
```yaml
post:
operationId: create/entries
requestBody:
content:
application/vnd.api+json:
schema:
required: ...
properties:
data:
type: object
required: ...
properties:
type: ...
id: ...
links: ....
attributes: ...
relationships:
type: object
properties:
blog:
$ref: '#/components/schemas/reltoone'
blogHyperlinked:
$ref: '#/components/schemas/reltoone'
authors:
$ref: '#/components/schemas/reltomany'
comments:
$ref: '#/components/schemas/reltomany'
commentsHyperlinked:
$ref: '#/components/schemas/reltomany'
suggested:
$ref: '#/components/schemas/reltomany'
suggestedHyperlinked:
$ref: '#/components/schemas/reltomany'
tags:
$ref: '#/components/schemas/reltomany'
featuredHyperlinked:
$ref: …
```
=> Specify required relationship fields in OpenAPI schema

CHANGELOG.md, example/tests/__snapshots__/test_openapi.ambr, rest_framework_json_api/schemas/openapi.py
Add `additionalProperties: true` to the `resource` schema's `attributes` and `relationships` objects to document the fact that these objects will contain keys.
```patch
components:
schemas:
resource:
type: object
required:
- type
- id
additionalProperties: false
properties:
type:
$ref: '#/components/schemas/type'
id:
$ref: '#/components/schemas/id'
attributes:
type: object
+           additionalProperties: true
relationships:
type: object
+           additionalProperties: true
links:
$ref: '#/components/schemas/links'
meta:
$ref: '#/components/schemas/meta'
```
Discovered during an OpenAPI schema validation run as the `included` array was found to contain too many keys in those objects.
=> Add additionalProperties to includes' attributes and relationships

CHANGELOG.md, rest_framework_json_api/__init__.py
I am not sure how much longer it will take for Django REST framework to be released. I therefore propose we release now and will do another release when DRF 3.15 is released.
=> Release 6.1.0

.github/workflows/tests.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Python 3.7 is end of life since 27 Jun 2023, so we can remove support for it.
=> Removed support for Python 3.7

setup.py
This was missed when removing Python 3.7.
=> Increased minimum Python version

CHANGELOG.md, README.rst, docs/getting-started.md, tox.ini
Django support for version 4.0 ended 01 Apr 2023 so according to our policy we can remove it.
=> Removed support for Django 4.0

AUTHORS, CHANGELOG.md, rest_framework_json_api/serializers.py, tests/test_serializers.py
For serializers inheriting from `ModelSerializer` that declare additional fields, the order of field names returned by `get_field_names` can get unpredictable. It is not necessarily following alphabetical order but can also change between several runs of schema generation (tested with `drf-spectacular` for instance). 
This is especially true when a `ModelSerializer` has `fields = "__all__"` and inherits from several serializers.
```python
class MyTestModel(DJAModel):
verified = models.BooleanField(default=False)
uuid = models.UUIDField()
class AnotherSerializer(serializers.Serializer):
ref_id = serializers.CharField()
reference_string = serializers.CharField()
class MyTestModelSerializer(AnotherSerializer, serializers.ModelSerializer):
an_extra_field = serializers.CharField()
class Meta: …
```
=> Ensure that ModelSerializer fields are in same order than in DRF

.github/workflows/tests.yml, CHANGELOG.md, README.rst, docs/getting-started.md, requirements/requirements-optionals.txt, setup.cfg, setup.py, tox.ini
Added support for Python 3.12.
=> Added Python 3.12 support

CHANGELOG.md, example/tests/unit/test_renderers.py, rest_framework_json_api/renderers.py
[Attributes](https://jsonapi.org/format/#document-resource-objects) member is actually optional and may not be rendered if there are no serializer attribute fields. But currently it does. The renderer though already made sure, that relationships are not rendered if there are not any, so this change makes it more consistent.
=> Avoided that an empty attributes dict is rendered

docs/conf.py
Our current stable docs show in an [old theme](https://django-rest-framework-json-api.readthedocs.io/en/stable/). This should make sure that the rtd theme is used locally as remotely.
=> Use sphinx theme locally and on rtd as extension

CHANGELOG.md, README.rst, docs/getting-started.md, tox.ini
As per our policy, removed support for outdated Django 4.1.
=> Removed support for Django 4.1

CHANGELOG.md, README.rst, docs/getting-started.md, example/urls_test.py, setup.py, tox.ini
Run django-upgrade --target-version 4.2
=> Drop support for Django 3.2

CHANGELOG.md, rest_framework_json_api/utils.py, tests/test_views.py
Fixes #1004
This got introduced when implementing #1070 This is fixed that the pointer is not set specifically when serializer can not be retrieved.
=> Avoided shadowing of exception when rendering errors

CHANGELOG.md, example/tests/integration/test_non_paginated_responses.py, example/tests/integration/test_pagination.py, example/tests/integration/test_sparse_fieldsets.py, example/tests/test_filters.py, example/tests/unit/test_renderer_class_methods.py, example/views.py, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, tests/serializers.py, tests/test_relations.py, tests/test_views.py
Fixes #1216
Fixes #332
The rendering of objects is flawed as the DJA renderer does most of the serialization again which should actually only be done by the serializer. Even though I reduced the readable fields in the serializer when sparse fields is used, it did not work.
I already adjusted `extract_attributes` that it uses the fields provided by the serializer. To adjust `extract_relationships` is more complex. Therefore, to get this critical issue fixed I also added code to exclude fields in the renderer when sparse fields is used.
=> Ensured that sparse fields only applies when rendering not when parsing

setup.cfg
Removed obsolete warning filter
=> Removed obsolete warning filter

CHANGELOG.md, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, tests/serializers.py, tests/test_views.py, tests/views.py
Fixes #1228
URL field is considered a field in DRF but it is not in JSON:API spec therefore we may not exclude it during sparse fields. ID on the other hand is a required field and may not be filtered out either as we allow in DJA to overwrite primary key of model.
=> Ensured that URL and id field are kept when using sparse fields

CHANGELOG.md, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, tests/conftest.py, tests/models.py, tests/serializers.py, tests/test_views.py, tests/views.py
Addresses #1233
`URL_FIELD_NAME` is usually used as self-link in links. However, the field name should be allowed to be overwritten as long as the field type is not HyperlinkedIdentifyField which `HyperlinkedModelSerializer` uses.
=> Re-enabled overwriting of URL field

CHANGELOG.md, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, tests/test_views.py
Fixes #1238
When a sparse field is set to an empty value no fields (attributes/relationships) should be rendered whereas currently it rendered all fields.
=> Ensured that no fields are returned when sparse fields is set to an empty value

CHANGELOG.md, rest_framework_json_api/__init__.py
Another release to get the two regressions out of the way, not to hinder anyone from upgrading.
=> Release 7.0.2

AUTHORS, CHANGELOG.md, rest_framework_json_api/utils.py, tests/test_utils.py
Fixes #1244 
- handle zero as valid pk/id in get_resource_id util method
- update tests to include cases where ID is zero
=> Handle zero as valid pk/id in get_resource_id util method

CHANGELOG.md, example/tests/test_views.py, rest_framework_json_api/parsers.py
As of DRF upstream change https://github.com/encode/django-rest-framework/pull/9455 our current tests with DRF master are failing. The reason being is that previous to the above change, parser attribute errors would get swallowed.
After this upstream change it occurred that we actually have an error in our code that an attribute error gets hidden and instead of raising a 500-error the code would just continue.
This happened when patching a To-Many relationship with `RelationshipView` with `None`. However, the [JSON:API spec](https://jsonapi.org/format/#crud-updating-to-many-relationships) defines that for emptying a To-Many relationship, caller needs to pass empty array instead of None.
So this PR ensures that when passing on `None` when patching To-Many relationship, a proper request …
=> Ensured that patching a To-Many relationship correctly raises request error

CHANGELOG.md, docs/usage.md, example/tests/test_openapi.py, rest_framework_json_api/schemas/openapi.py
Addresses #1082
As discussed, we deprecate built-in support for OpenAPI schema generation and promote [drf-spectacular-json-api](https://github.com/jokiefer/drf-spectacular-json-api/) instead.
=> Deprecated built-in support for OpenAPI schema generation

.readthedocs.yaml
This is needed for Sphinx 8. Fixing current [docs build issue](https://readthedocs.org/projects/django-rest-framework-json-api/builds/25860244/).
=> Bumped docs Python version to 3.10

.github/workflows/tests.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Python 3.13 will only be supported by [Django 5.1 and above](https://forum.djangoproject.com/t/backport-python-3-13-support-in-django-5-0/34671).
Currently, 3.13 has not been released yet on [Github](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) so using Python 3.13-dev. This should be removed once it is released.
Additionally, DRF made a [change](https://github.com/encode/django-rest-framework/pull/9527/files) to how description is retrieved. Tests with DRF 3.15 are failing because of that, so only testing on drfmaster. However, as schema support is deprecated anyway, I suppose we can still mark DJA to support Python 3.13 before DRF releases another version. 
As only drfmaster is tested for Python 3.13 it does not make sense to ignore it. As of …
=> Added support for 3.13

.github/workflows/tests.yml
This has been released now on GitHub.
=> Use final release of 3.13

CHANGELOG.md, rest_framework_json_api/__init__.py
Another release especially to get the deprecation of OpenAPI schema out there, so people start switching to drf-spectacular-json-api.
=> Release 7.1.0

.github/workflows/tests.yml, CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Remove Python 3.8 which is EOL per [PEP 569](https://peps.python.org/pep-0569/)
=> Removed support for Python 3.8

README.rst
Fixes #1269
This PR updates the documentation to include the `--pythonpath .` option when running `django-admin` commands to set up the example app.
=> Update documentation to include --pythonpath to set up the example app

CHANGELOG.md, README.rst, docs/getting-started.md, setup.py, tox.ini
Added new Django REST framework 3.16 and as of our policy as we only support the two last DRF releases dropped support for Django REST framework 3.14.
=> Added support for Django REST framework 3.16

CHANGELOG.md, README.rst, docs/getting-started.md, tox.ini
According to [Django project](https://www.djangoproject.com/download/) added support for Django 5.2 and removed outdated Django 5.0.
=> Updated Django support

CHANGELOG.md, rest_framework_json_api/renderers.py, rest_framework_json_api/serializers.py, rest_framework_json_api/utils.py, tests/conftest.py, tests/test_utils.py
Fixes #203
Fixes #871
Fixes #1053
`include` query parameter can be in a different formats like `dasherized` when `JSON_API_FORMAT_FIELD_NAMES` is set. In some cases, this was not taken into account when reading the `include` parameter. I have moved the logic of underscoring into the `get_included_resources` so it will be correctly processed in all use cases.
=> Ensured that `include` param is properly underscored

requirements/requirements-optionals.txt
Seems when merging #1289 this change went missing.
=> Set django polymorphic version to newest
